# -*- coding: utf-8 -*-
"""Copia de CC3001 - Otoño 2023 - Tarea1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11RlTopYJKCpdMDxhXdmHkHpsVD2KhK3e

# CC3001 Otoño 2023 Tarea 1

# Pilas de arena abelianas

### Profesores
Sección 1 Iván Sipirán •
Sección 2 Patricio Poblete •
Sección 3 Nelson Baloian

# Introducción
El objetivo de esta tarea es estudiar un problema inspirado en un fenómeno físico, a través de un modelo matemático, el cual si bien es sencillo, produce resultados que presentan una estructura muy interesante.

<img src="https://ivan-sipiran.com/downloads/arena.png" alt= “” width="200">

La idea es que si uno va formando una pila de arena, llega un momento en que se produce un derrumbe, y la arena de esa pila se derrama hacia los lugares vecinos, estos a su vez se pueden derrumbar, y el proceso continúa hasta que finalmente se estabiliza.

Para estudiar este proceso, usaremos un modelo ultra simplificado. Supondremos que la arena se deposita sobre una superficie plana, la cual está dividida en pequeñas celdas cuadradas, las cuales forman un tablero como se muestra en la siguiente figura:

<img src="https://ivan-sipiran.com/downloads/tablero.png" alt= “” width="100">

El modelo supone que si se apilan demasiados granos de arena en una celda, se produce un derrumbe. En particular, la regla es que si en una celda hay 4 o más granos, se le quitan 4 granos, que se reparten equitativamente hacia las celdas vecinas en los cuatro puntos cardinales.

Para simular este proceso, supondremos que cada celda almacena un número entero, que es la cantidad de granos almacenados en su interior. Aplicando la regla antes descrita (y suponiendo que las celdas que aparecen vacías tienen cero granos), desde la configuración

<img src="https://ivan-sipiran.com/downloads/tablero1.png" alt= “” width="100">

se pasaría a

<img src="https://ivan-sipiran.com/downloads/tablero2.png" alt= “” width="100">

Cuando hay más de una casilla con exceso de granos de arena, la regla se puede aplicar a ellas en cualquier orden y el resultado final es el mismo. Esta propiedad es la que hace que estas pilas de arena se llamen abelianas.

La idea es partir desde una configuración inicial, y luego aplicar esta regla en todos los casilleros que se pueda, hasta que no quede ninguno que tenga 4 o más granos de arena. Esa configuración final la vamos a visualizar asignando un color distinto a cada número de granos.

En particular, nos va a interesar estudiar lo que ocurre cuando la configuración inicial tiene todas las celdas vacías, excepto la del centro, en la cual hay $N$ granos de arena (donde $N$ es un parámetro del problema).

Note que en teoría el tablero es infinito en el sentido que siempre hay espacio para colocar los granos de arena que se van distribuyendo. Para su simulación, usted debe calcular un tamaño del tablero lo suficientemente grande como para estar seguro que ningún grano de arena se salga hacia afuera de los bordes (calcule la máxima área que se puede cubrir con $N$ granos de arena, y después calcule cuan grande debe ser el tablero  para poder contener esa área).

# Tarea

## Parte 1
Usted debe escribir una función en Python llamada ``arena``, tal que dado un valor de $N$, simule el proceso anteriormente descrito hasta que se estabilice. El programa debe contar e imprimir el número total de veces que se aplicó la regla que distribuye granos de arena hacia los vecinos. Además, debe visualizar en la pantalla el tablero resultante, usando los métodos que se describen más adelante.

Por ejemplo, al simular con $N=10000$, la figura que resulta es

<img src="https://ivan-sipiran.com/downloads/tablero3.png" alt= “” width="250">

La idea va a ser ejecutar la función con un valor de $N$ dado por el profesor ($N=128$) y luego con valores crecientes de $N$, hasta el mayor número que pueda alcanzar dentro de un tiempo de ejecución razonable.

Escriba a continuación la definición de su función:
"""

import matplotlib.pyplot as plt
import numpy as np
import math

def arena(N):
  r= int(math.sqrt(N / math.pi))  #Radio circulo

  diametro = int(r * 2.2)

  matriz=np.zeros((diametro,diametro)) #Creamos una matriz llena de ceros con un tamaño tal que que queden todos los granos de arena dentro
  n=len(matriz)#Largo de la matriz

  contador1=0#Valor inicial del contador del numero de reglas
  matriz[int((n-1) /2)][int((n-1) /2)]=N #Posicionamos el N al centro de la matriz


  while np.max(matriz)>=4: #Condición suficiente para que el ciclo continue y no pare hasta que todos los granos de arena cumplan la regla
    for i in range(n): #Filas
      for j in range(n):#Columnas
        if matriz[i][j]>=4:

          matriz[i][j]=matriz[i][j]-4#Le restamos 4 a todos los elementos que cumplan el if
          contador1=contador1+1 #Vamos sumandole 1 al contador cada vez que se cumple la regla

          if i>0: #Condicion impuesta para que no haya problemas con los indices
            matriz[i-1][j]=matriz[i-1][j]+1 #norte

          if j>0:
            matriz[i][j-1]=matriz[i][j-1]+1 #oeste

          if i<n-1:
            matriz[i+1][j]=matriz[i+1][j]+1#sur

          if j<n-1:
            matriz[i][j+1]=matriz[i][j+1]+1#este


  plt.matshow(matriz)
  plt.show()
  return contador1

"""Explique aquí cómo calculó el tamaño que necesita tener el tablero.

$Teniendo$ $entonces$ $que$ $colocamos$ $N$ $granos$ $de$ $arena$ $en$ $el$ $centro$ $del$ $tablero,$ $y$ $teniendo$ $en$ $cuenta$ $tambien$ $las$ $reglas$ $definidas$ $con$ $anterioridad,$ $pongamonos$ $en$ $el$ $caso$ $donde$ $todos$ $los$ $granos$ $de$ $arena$ $estan$ $esparcidos$ $por$ $el$ $tablero$ $de$ $tal$ $forma$ $que$ $solo$ $hay$ $1$ $por$ $cada$ $cuadrado$ $del$ $tablero.$ $Este$ $seria$ $el$ $caso$ $mas$ $extremo$ $de$ $todos,$ $y$ $con$ $este$ $nos$ $quedaremos$ $porque$ $tenemos$ $una$ $cota$ $superior$ $muy$ $buena$ $para$ $el$ $tamaño$ $de$ $la$ $matriz.$ $Ahora,$ $a$ $medida$ $que$ $el$ $N$ $va$ $aumentando$ $podemos$ $notar$ $que$ $se$ $forma$ $una$ $figura$ $reconocible,$ $un$ $circulo.$ $Este$ $lugar$ $geometrico$ $es$ $el$ $que$ $se$ $forma$ $a$ $medida$ $que$ $se$ $van$ $ejecutando$ $las$ $reglas,$ $por$ $lo$ $que$ $ahora$ $que$ $estamos$ $en$ $el$ $caso$ $mas$ $extremo,$ $podemos$ $decir$ $que$ $el$ $area$ $maxima$ $que$ $cubriran$ $N$ $granos$ $de$ $arena,$ $seria$ $una$ $circulo$ $de$ $cierto$ $radio$ $que$ $calcularemos$ $enseguida:$

$Area$ $maxima=$ $Pi*r**2=N,$ $donde$ $esta$ $igualdad$ $la$ $dedujimos$ $diciendo$ $que$ $cada$ $cuadrado$ $tiene$  $solo$ $un$ $grano$ $de$ $arena$ $formando$ $el$ $circulo.$ $($ $Asumimos$ $ademas$ $que$ $cada$ $grano$ $de$ $arena$ $tiene$ $una$ $unidad$ $de$ $area)$

$Por$ $lo$ $tanto,$ $despejando$ $r,$ $concluimos$ $que:$
$r=$ $sqrt(N / Pi)$

$Ya$ $teniendo$ $el$ $radio,$ $podemos$ $definir$ $el$ $tamaño$ $de$ $la$ $matriz$ $de$ $ceros,$ $diciendo$ $que$ $para$ $cualquier$ $tamaño$ $de$ $esta$ $que$ $sea$ $mayor$ $a$ $r,$ $podemos$ $cubrir$ $todo$ $el$ $circulo$ $que$ $cubren$ $los$ $granos$ $de$ $arena.$ $Por$ $lo$ $que$ $para$ $estar$  $($ $porque$ $pueden$ $haber$ $ciertos$ $errores$ $al$ $calcular$ $con$ $la$ $raiz),$ $eligimos$ $el$ $diametro,$ $es$ $decir,$ $dos$ $veces$ $el$ $radio,$ $y$ $así,$ $se$ $elige$ $el$ $tamaño$ $de$ $la$ $matriz.$

$En$ $conclusión:$

$Tamaño$ $matriz> r,$
$Area= pi*r**2$

Ahora ejecute la función para $N=128$:
"""

arena(128)

"""A continuación ejecute la función para el valor más grande de $N$ que consiga alcanzar en un tiempo razonable:"""

arena(12000) # reemplace N por el valor máximo que alcanzó a procesar
#Se demoro 1 minuto con 42 segundos

"""## Parte 2
Observe que cuando en una celda hay un número grande de granos de arena, es muy ineficiente ir quitándole de 4 en 4, y sería mejor quitar de una sola vez lo más que se pueda. Podemos mejorar nuestro programa si cambiamos la regla de distribución, y decimos que si en una celda hay un número de granos de arena mayor o igual a 4, le quitamos de una sola vez el mayor múltiplo de 4 posible, y todos esos granos lo repartimos equitativamente entre los vecinos de los cuatro puntos cardinales. Escriba una versión modificada de su función de acuerdo a esta nueva regla.


"""

def arena2(N):
  r= int(math.sqrt(N / math.pi))  #Radio circulo

  diametro = int(r * 2.2)

  matriz=np.zeros((diametro,diametro)) #Creamos una matriz llena de ceros con un tamaño tal que que queden todos los granos de arena dentro
  n=len(matriz)#Largo de la matriz

  contador2=0#Valor inicial del contador del numero de reglas
  matriz[int((n-1) /2)][int((n-1) /2)]=N #Posicionamos el N al centro de la matriz


  while np.max(matriz)>=4: #Condición suficiente para que el ciclo continue y no pare hasta que todos los granos de arena cumplan la regla
    for i in range(n): #Filas
      for j in range(n):#Columnas
        if matriz[i][j]>=4:





          contador2=contador2+1 #Vamos sumandole 1 al contador cada vez que se cumple la regla

          if i>0: #Condicion impuesta para que no haya problemas con los indicies
             #norte
              matriz[i-1][j]+=matriz[i][j]//4

          if j>0:
               matriz[i][j-1]+=matriz[i][j]//4#oeste

          if i<n-1:
               matriz[i+1][j]+=matriz[i][j]//4#sur

          if j<n-1:
               matriz[i][j+1]+=matriz[i][j]//4#este

          matriz[i][j]%=4 #Resto de la división por 4 entrega el valor final de un elemento de la matriz



  plt.matshow(matriz)
  plt.show()
  return contador2   #Retonarmos la matriz final y el valor del contador como una tupla

"""Ahora ejecute la función para $N=128$:"""

arena2(128)

"""A continuación ejecute la función para el valor más grande de  𝑁  que consiga alcanzar en un tiempo razonable. Note que éste número no necesariamente es el mismo que para la función anterior:"""

arena2(30000) # reemplace N por el valor máximo que alcanzó a procesar
#se demoró 2 minutos y 9 segundos

"""## Parte 3
Compare a través de una tabla y un gráfico el número de aplicaciones de la regla que hace el programa en la Parte 1 y el de la Parte 2, para los distintos valores de $N$ que usted haya calculado.

Discuta si valió la pena la optimización y discuta también (pero no implemente) otras posibles optimizaciones que se le ocurran.

$A$ $continuación$ $compararemos$ $cada$ $valor$ $del$ $contado$ $para$ $cada$ $una$ $de$ $las$ $versiones$ $de$ $la$ $función$.
"""

import matplotlib.pyplot as plt

fig, ax = plt.subplots()
N = [10,100,500, 1000,5000,10000,20000]
Funciones = {'Arena1':[2,225,4702,18226,466188,1830917,7274878], 'Arena2':[1,149,3031,11724,307656,1196817,4746155]}
ax.plot(N, Funciones['Arena1'], label = 'Arena1',marker='o')
ax.plot(N, Funciones['Arena2'], label = 'Arena2',marker='o')
ax.legend(loc = 'upper left')
ax.set_xlabel("N", fontdict = {'fontsize':14, 'fontweight':'bold', 'color':'tab:blue'})
ax.set_ylabel("Valor del contador")
ax.set_title('Comparación de los contadores', loc = "left", fontdict = {'fontsize':14, 'fontweight':'bold', 'color':'tab:blue'})


plt.show()

"""Arena 1

| N     | Contador |
|-------|----------|
| 10    | 2        |
| 100   | 225      |
| 500   | 4702     |
| 1000  | 18226    |
| 5000  | 466188   |
| 10000 | 1830917  |
| 20000 | 7274878  |



Arena 2

| N     | Contador |
|-------|----------|
| 10    | 1        |
| 100   | 149      |
| 500   | 3031     |
| 1000  | 11724    |
| 5000  | 307656   |
| 10000 | 1196817  |
| 20000 | 4746155  |

**Analizando el grafico y la tabla podemos apreciar que para valores pequeños de N tales como 1000 o 5000, no hay un gran margen de diferencia entre ambas funciones, es decir, el tiempo de ejecución de arena2 no es tan diferente al de arena 2 como para decir que efectivamente vale la pena haber hecho esta optimización. Pero esto cambia cuando N es mas grande. Para valores desde 10000 en adelante, hay una diferencia notoria en los contadores de cada uno, lo que se traduce en un tiempo de ejecución muy alto para arena1, y abajo para 2, lo cual, puede ser crucial para situaciones donde se requiera que se entregue el resultado en el menor tiempo posible. En resumen:
Pára N pequeño: Es practicamente lo mismo usar uno o el otro;
Para N grande: Es mucho mas eficiente usar arena2**

**Ahora, para aumentar la eficiencia del algoritmo, podriamos en vez de usar iteraciones, usar recursión, aunque no necesariamente puede que aumente la eficiencia, no esta demas intentarlo y quizas salga en menos lineas de codigo. Otra forma de aumentar la eficincia puede ser ver ciclos que se formen al tener 4 granos, de tal forma que se implente un if tal que se ejecute una instrucción que haga que se tenga todo en un solo paso y no en varios.**
"""
