# -*- coding: utf-8 -*-
"""Copia de  CC3001 2023-1Tarea4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c35qDiekaVjWL0ZRxf0-ypJ_-gtND0Hz

# CC3001 Otoño 2023 Tarea 4
# Generación de código

Profesores: Iván Sipirán / Nelson Baloian / Patricio Poblete

El objetivo de esta tarea es aprender sobre la manipulación de árboles que representan fórmulas. Hay muchas cosas que uno puede hacer con estos árboles, y en esta tarea nos enfocaremos en particular en algo que los compiladores hacen: la **generación de código** para evaluar fórmulas.

Específicamente, el problema es: dada una fórmula, generar una secuencia de instrucciones elementales que la evalúen. Por ejemplo, dada una fórmula como

```
(a+b)*(c-d)
```

se podría generar código como el siguiente:

```
t1=a+b
t2=c-d
t3=t1*t2
```

Las instrucciones elementales son siempre de la forma ``ti=x op y``, donde ``ti`` es una variable temporal, ``x`` e ``y`` pueden ser variables o números, y ``op`` es un operador. Uno va creando variables ``t1``, ``t2``, ... a medida que las necesita, y la última de ellas es la que almacena el valor final de la fórmula.

Las fórmulas pueden ser arbitrariamente complicadas, como por ejemplo la fórmula

$$
(2-p\,q)\left( \frac{1}{n}+\frac{1}{p+q}\right)
$$

la cual escribimos como

```
(2-p*q)*(1/n+1/(p+q))
```

y cuyo código generado podría ser,

```
t1=p*q
t2=2-t1
t3=1/n
t4=p+q
t5=1/t4
t6=t3+t5
t7=t2*t6
```

El objetivo de esta tarea es que usted implemente una función que, dado un árbol ya construído, lo recorra para generar una secuencia de instrucciones elementales que lo evalúe.

A continuación usted encontrará clases ``Nodoi``, ``Nodoe`` y ``Arbol`` que implementan árboles que representan fórmulas. La clase ``Arbol`` viene con un constructor que recibe un string como parámetro, el cual contiene una fórmula, y este constructor se encarga de transformar la fórmula de string a árbol, de modo que usted no necesita preocuparse de eso. Para simplificar, la fórmula solo podrá contener variables de una sola letra, números de un solo dígito, y sin espacios. Los operadores permitidos son solo suma, resta, multiplicación y división. No hay operador menos unario.

Usted tienen que implementar para la clase ``Arbol`` una función ``codigo`` que al ser invocado genere una secuencia de instrucciones elementales para evaluar la fórmula representada por ese árbol, y la retorne en forma de una lista (de Python).
"""

# Ejecutar esto para poder visualizar los árboles

!pip install aed-utilities

import aed_utilities as aed

class Nodoi:
    def __init__(self, izq, info, der):
        self.izq=izq
        self.info=info
        self.der=der







class Nodoe:
    def __init__(self, info):
        self.info=info




class Arbol:
    def __init__(self,formula):
        global k
        global s
        s=formula+";" # agregamos una marca de fin de la entrada
        k=0 # indica próximo caracter por procesar
        # definimos funciones para analizar la fórmula
        def expresion(): # retorna puntero a la raíz de un árbol que representa a la fórmula s
            global k
            global s
            a=factor()
            while s[k]=="+" or s[k]=="-":
                op=s[k]
                k+=1
                b=factor()
                a=Nodoi(a,op,b)
            return a
        def factor():
            global k
            global s
            a=termino()
            while s[k]=="*" or s[k]=="/":
                op=s[k]
                k+=1
                b=termino()
                a=Nodoi(a,op,b)
            return a
        def termino(): # posible constante, variable o formula parentizada
            global k
            global s
            if s[k].isalpha() or s[k].isdigit():
                a=Nodoe(s[k])
                k+=1
                return a
            if s[k]=="(": # fórmula parentizada
                k+=1
                a=expresion()
                if s[k]!=")":
                    print("Error: Falta cierra paréntesis: "+formula[k:])
                    assert False
                k+=1
                return a
            print("Error: Falta variable, número o abre paréntesis: "+formula[k:])
            assert False

        a=expresion()
        if s[k]!=";":
            print("Error: Basura al final de la fórmula: "+formula[k:])
            assert False
        self.raiz=a

    def codigo(self):
        # Función auxiliar para generar variables temporales t_i
        def generar_variable_temporal():
            nonlocal contador_temporal  #Se decalara una variable  nonlocal para que se pueda modificar en el ambiente exterior.
            contador_temporal += 1
            return "t" + str(contador_temporal)

        # Función recursiva para generar las expresiones paso a paso
        def generar_expresion(nodo):
            if isinstance(nodo, Nodoe):#Condición necesaria para ver qué ejecutar,dado que nodo puede pertencer tanto a la clase Nodoe como Nodoi, y en cada caso hay que abordarlo de distinta manera.
                return nodo.info  #En el caso de que nodo sea una instancia de la clase Nodoe, solamnte retorna su información
            elif isinstance(nodo, Nodoi):#En el caso de que sea un nodo interno, debemos hacer recursion
                op = nodo.info
                if op in "+-*/":
                    izq_exp = generar_expresion(nodo.izq)
                    der_exp = generar_expresion(nodo.der)
                    ti = generar_variable_temporal()
                    codigo.append(ti + " = " + izq_exp + " " + op + " " + der_exp)
                    return ti
                else:
                    raise ValueError("Operador inválido: " + op) #Esta parte del codigo es para parar el programa en el caso de que no hayan operadores definidos.


        codigo = []  #Almacena las vaiables generadas y despues las va retornandod de apoco
        contador_temporal = 0  # Esto sirve para llevar cuenta de las variables temporales que se van a ir generando


        resultado = generar_expresion(self.raiz)
        codigo.append(resultado)

        return codigo

    def dibujar(self):
      btd = aed.BinaryTreeDrawer(fieldData="info", fieldLeft="izq", fieldRight="der", classNone=Nodoe)
      btd.draw_tree(self, "raiz")

"""A continuación probamos esta funcionalidad con varias fórmulas de ejemplo. Para ver si el árbol fue construido correctamente, lo dibujamos."""

Arbol("a+c").dibujar()

Arbol("(a+b)*(c-d)").dibujar()

Arbol("((((a+b)+c)+d)+e)").dibujar()

"""## Resultados

En esta sección probamos la generación de código que usted tiene que escribir. Mientras usted no sustituya la función ``codigo`` provisoria que viene en la definición de la clase, va a aparecer la lista que generamos ahí. Primero vamos a definir una función ``probar`` que genera el código a partir de una fórmula dada e imprime el resultado:
"""

def probar(formula):
    a=Arbol(formula)
    for x in a.codigo():
        print(x)

"""A continuación probamos con varias fórmulas. Además de las fórmulas dadaas, usted tiene que agregar tres ejemplos adicionales."""

probar("a+1")

probar("(a+b)*(c-d)")

probar("(2-p*q)*(1/n+1/(p+q))")

probar("((((a+b)+c)+d)+e)")

probar("(a+(b+(c+(d+e))))")

probar("a")

"""## Para los que quieran aprender más (opcional)

Suponga que hay escasez de variables temporales, así que se le ha pedido que trate de reciclarlas lo más posible, y solo crear nuevas variables ``ti`` cuando sea estrictamente necesario. Por ejemplo, para la fórmula

```
((a+b)*c)+((d-e)/f)
```

si generamos código como lo hemos hecho en los ejemplos anteriores (código de la izquierda), se usan 5 variables temporales, pero el código de la derecha muestra que se puede evaluar usando solo 2:

```
t1=a+b               t1=a+b
t2=t1+c              t1=t1*c
t3=d-e               t2=d-e
t4=t3/f              t2=t2/f
t5=t2+t4             t1=t1+t2
```

Piense cómo se podría modificar su algoritmo para que use el mínimo posible de variables temporales.

No es necesario que implemente nada, solo que considere cómo se podría hacer. Si se le ocurre algo interesante, puede escribirlo al final de su tarea, pero no es obligatorio ni influye en la nota. ¡La satisfacción de poder resolver el problema es su propia recompensa!
"""